#!/bin/bash
#
# Read in the configuration.
CONFIG="/boot/config/plugins/file.activity/config.json"

# Start file activity if it is enabled.
if [ "$(jq -r '.enable' "$CONFIG" 2>/dev/null)" = "true" ]; then
	/usr/local/emhttp/plugins/file.activity/scripts/rc.file.activity start 1>/dev/null
fi
